src/main/resources/application.properties
[confluence page](https://wanna-go-home.atlassian.net/wiki/spaces/GOHOME/pages/3342578/go-home-db+PostgreSQL)
DB 서버 주소가 바뀌어서 PR을 날림.
테스트 안해봄ㅠ
=> Update db server address

build.gradle, src/main/java/com/springboot/intelllij/domain/LensEntity.java
- Change table schema : db name, column name 등에는 대문자를 사용하는게 아니라고 함. 기존에 `@Table(name = "\"Lens\"")` 같은 이상한 코드도 대문자가 섞여 있어서 저렇게 된 거였음. 그래서 table에서 대문자를 없앴음.
- Change column datatype
다음 column 들의 PostgreSQL에서의 data type이 text -> jsonb으로 바뀜
그래서 서버에서도 String -> JsonNode로 바꿈
```
productImage
demonstrationImage
per
```
=> Change column datatype : String to JsonNode

src/main/java/com/springboot/intelllij/controller/ReviewBoardController.java, src/main/java/com/springboot/intelllij/domain/ReviewBoardEntity.java, src/main/java/com/springboot/intelllij/domain/ReviewBoardPreview.java, src/main/java/com/springboot/intelllij/repository/ReviewBoardRepository.java, src/main/java/com/springboot/intelllij/services/FreeBoardService.java, src/main/java/com/springboot/intelllij/services/ReviewBoardService.java
free_board 와의 차이점은 
view_cnt가 없고, lens_id가 있음
```sql
CREATE TABLE public.review_board
(
id integer NOT NULL DEFAULT nextval('review_board_id_seq'::regclass),
title text COLLATE pg_catalog."default",
content text COLLATE pg_catalog."default",
user_id integer,
like_cnt integer DEFAULT 0,
created_at date DEFAULT now(),
lens_id integer NOT NULL,
CONSTRAINT review_board_pkey PRIMARY KEY (id)
)
```
=> Add basic APIs for review_board

build.gradle, src/main/java/com/springboot/intelllij/controller/FreeBoardController.java, src/main/java/com/springboot/intelllij/controller/ReviewBoardController.java, src/main/java/com/springboot/intelllij/domain/FreeBoardCommentEntity.java, src/main/java/com/springboot/intelllij/domain/FreeBoardEntity.java, src/main/java/com/springboot/intelllij/domain/FreeBoardViewEntity.java, src/main/java/com/springboot/intelllij/domain/ReviewBoardCommentEntity.java, src/main/java/com/springboot/intelllij/domain/ReviewBoardEntity.java, src/main/java/com/springboot/intelllij/domain/ReviewBoardViewEntity.java, src/main/java/com/springboot/intelllij/repository/FreeBoardCommentRepository.java, src/main/java/com/springboot/intelllij/repository/ReviewBoardCommentRepository.java, src/main/java/com/springboot/intelllij/services/FreeBoardCommentService.java, src/main/java/com/springboot/intelllij/services/ReviewBoardCommentService.java
ReviewBoard Entity 정의할 때 view_cnt를 까먹어서 안넘어가고 있었음.
그리하여 추가하겠음
=> Add view cnt

build.gradle, src/main/java/com/springboot/intelllij/controller/FreeBoardController.java, src/main/java/com/springboot/intelllij/controller/ReviewBoardController.java, src/main/java/com/springboot/intelllij/domain/FreeBoardCommentEntity.java, src/main/java/com/springboot/intelllij/domain/FreeBoardEntity.java, src/main/java/com/springboot/intelllij/domain/FreeBoardViewEntity.java, src/main/java/com/springboot/intelllij/domain/ReviewBoardCommentEntity.java, src/main/java/com/springboot/intelllij/domain/ReviewBoardEntity.java, src/main/java/com/springboot/intelllij/domain/ReviewBoardViewEntity.java, src/main/java/com/springboot/intelllij/repository/FreeBoardCommentRepository.java, src/main/java/com/springboot/intelllij/repository/ReviewBoardCommentRepository.java, src/main/java/com/springboot/intelllij/services/FreeBoardCommentService.java, src/main/java/com/springboot/intelllij/services/ReviewBoardCommentService.java
#26  에 이어서 GET method를 구현함.
/api/boards/free-board/{id}/comments
/api/boards/review-board/{id}/comments
2가지이며 아직 댓글 pagenation은 없음
=> Wgh 86 get comment

src/main/java/com/springboot/intelllij/controller/AccountController.java, src/main/java/com/springboot/intelllij/domain/BaseEntity.java, src/main/java/com/springboot/intelllij/domain/BoardBaseEntity.java, src/main/java/com/springboot/intelllij/domain/CommentBaseEntity.java, src/main/java/com/springboot/intelllij/domain/FreeBoardCommentEntity.java, src/main/java/com/springboot/intelllij/domain/FreeBoardEntity.java, src/main/java/com/springboot/intelllij/domain/FreeBoardViewEntity.java, src/main/java/com/springboot/intelllij/domain/LensBaseEntity.java, src/main/java/com/springboot/intelllij/domain/LensEntity.java, src/main/java/com/springboot/intelllij/domain/LensPreviewEntity.java, src/main/java/com/springboot/intelllij/domain/ReviewBoardCommentEntity.java, src/main/java/com/springboot/intelllij/domain/ReviewBoardEntity.java, src/main/java/com/springboot/intelllij/domain/ReviewBoardViewEntity.java
상속을 이용해서 entity 정의 들 사이의 중복을 제거함. 
겸사겸사 Timestamp serialize 방식을 ISO8601 방식으로 변경함
=> Entity refactoring

src/main/java/com/springboot/intelllij/controller/UserController.java, src/main/java/com/springboot/intelllij/domain/UserInfoDTO.java, src/main/java/com/springboot/intelllij/exceptions/EntityNotFoundExceptionEnum.java, src/main/java/com/springboot/intelllij/repository/FreeBoardCommentRepository.java, src/main/java/com/springboot/intelllij/repository/FreeBoardRepository.java, src/main/java/com/springboot/intelllij/repository/ReviewBoardCommentRepository.java, src/main/java/com/springboot/intelllij/repository/ReviewBoardRepository.java, src/main/java/com/springboot/intelllij/services/AccountService.java
로그인한 유저의 
- 쓴 리뷰 갯수
- 쓴 글 갯수(자유게시판)
- 쓴 리뷰 댓글 갯수
- 쓴 댓글 갯수(자유게시판)
- 받은 좋아요 갯수(통합)
- 이메일
- 닉네임
을 반환하는 API
=> [Issue - 42] User Info

README.md
Fix https://github.com/wanna-go-home/Issue/issues/14
=> add ansible location

src/main/java/com/springboot/intelllij/controller/UserController.java, src/main/java/com/springboot/intelllij/domain/AccountEntity.java, src/main/java/com/springboot/intelllij/repository/AccountRepository.java, src/main/java/com/springboot/intelllij/services/AccountService.java, src/main/java/com/springboot/intelllij/utils/StringValidationUtils.java, src/main/java/com/springboot/intelllij/utils/TokenUtils.java
fix https://github.com/wanna-go-home/Issue/issues/3
- 이메일 형식 체크 추가
- 전화번호 형식 체크 추가 
- 회원가입시 형식체크가 모두 통과해야 할수있도록 변경
- 가독성 증가를 위해 account에서 accountEmai로 이름 변경
=> 회원가입 수정 - 이메일 체크, 전화번호 체크

src/main/java/com/springboot/intelllij/controller/FreeBoardController.java, src/main/java/com/springboot/intelllij/domain/FreeBoardUpdateDTO.java, src/main/java/com/springboot/intelllij/exceptions/EntityNotFoundExceptionEnum.java, src/main/java/com/springboot/intelllij/repository/FreeBoardCommentRepository.java, src/main/java/com/springboot/intelllij/repository/FreeBoardRepository.java, src/main/java/com/springboot/intelllij/services/FreeBoardService.java
=> FreeBoard Update/Delete methods

src/main/java/com/springboot/intelllij/controller/FreeBoardController.java, src/main/java/com/springboot/intelllij/controller/ReviewBoardController.java, src/main/java/com/springboot/intelllij/domain/BoardUpdateDTO.java, src/main/java/com/springboot/intelllij/repository/ReviewBoardCommentRepository.java, src/main/java/com/springboot/intelllij/repository/ReviewBoardRepository.java, src/main/java/com/springboot/intelllij/services/ReviewBoardService.java
=> 리뷰게시판 게시물 DELETE / PUT

src/main/java/com/springboot/intelllij/controller/FreeBoardController.java, src/main/java/com/springboot/intelllij/controller/ReviewBoardController.java, src/main/java/com/springboot/intelllij/exceptions/EntityNotFoundExceptionEnum.java, src/main/java/com/springboot/intelllij/services/FreeBoardService.java, src/main/java/com/springboot/intelllij/services/ReviewBoardService.java
AS-IS
```
{
"id": 7,
"account": "admin@admin.com",
"title": "string",
"content": "default test",
"viewCnt": 0,
"likeCnt": 0,
"replyCnt": 0,
"createdAt": "2020-10-05T22:17:16.867Z"
}
```
TO-BE
```
{
"id": 7,
"account": "admin@admin.com",
"title": "string",
"content": "default test",
"viewCnt": 0,
"likeCnt": 0,
"replyCnt": 0,
"createdAt": "2020-10-05T22:17:16.867Z",
"nickname": "admin" #  nickname을 추가한다
}
```
closes wanna-go-home/issue#32
=> FreeBoard / ReviewBoard nickname 추가

src/main/java/com/springboot/intelllij/domain/FreeBoardCommentEntity.java, src/main/java/com/springboot/intelllij/services/FreeBoardCommentService.java
- 대댓글이 3개 이상 반환되던것 수정
- bundle size가 업데이트 안되던것 수정
- 글아이디 35, 댓글아이디 11의 예시
```json
[
{
"id": 11,
"accountId": "admin@admin.com",
"postId": 35,
"content": "\"string\"",
"likeCnt": 0,
"createdAt": "2020-12-17T22:40:49.990Z",
"depth": 0,
"bundleId": 11,
"bundleSize": 5
},
{
"id": 15,
"accountId": "admin",
"postId": 35,
"content": "Child-Comment-1",
"likeCnt": 0,
"createdAt": "2020-12-20T11:56:03.752Z",
"depth": 1,
"bundleId": 11,
"bundleSize": 0
},
{
"id": 16,
"accountId": "admin",
"postId": 35,
"content": "Child-Comment-2",
"likeCnt": 0,
"createdAt": "2020-12-20T11:56:10.160Z",
"depth": 1,
"bundleId": 11,
"bundleSize": 0
},
{
"id": 17,
"accountId": "admin",
"postId": 35,
"content": "Child-Comment-3",
"likeCnt": 0,
"createdAt": "2020-12-20T11:56:28.423Z",
"depth": 1,
"bundleId": 11, …
```
=> [Hotfix] 댓글 / 대댓글 버그수정

src/main/java/com/springboot/intelllij/services/FreeBoardService.java, src/main/java/com/springboot/intelllij/services/ReviewBoardService.java
GET API에 기능을 추가하여 viewCount++ 해주도록 하자
해당 APIs
- GET /api/boards/free-board/{id}
- GET /api/boards/review-board/{id}
fix https://github.com/wanna-go-home/Issue/issues/57
=> increase viewcount wanna-go-home/issue#57

src/main/java/com/springboot/intelllij/controller/ReviewBoardController.java, src/main/java/com/springboot/intelllij/domain/CommentBaseEntity.java, src/main/java/com/springboot/intelllij/domain/FreeBoardCommentEntity.java, src/main/java/com/springboot/intelllij/repository/ReviewBoardCommentRepository.java, src/main/java/com/springboot/intelllij/services/FreeBoardCommentService.java, src/main/java/com/springboot/intelllij/services/ReviewBoardCommentService.java
fix https://github.com/wanna-go-home/Issue/issues/48
- 리뷰 게시판 댓글 / 대댓글 관련 UD 추가
- 생긴게 아예 자유게시판하고 동일해졌음
- 자유게시판과 거의 비슷하게 되어버려서 리팩토링 해야할듯
=> 리뷰 게시판 댓글 UD

src/main/java/com/springboot/intelllij/services/ReviewBoardCommentService.java
안바뀐데가 아직 있어서 빌드 실패했었음.
아묻따 머지하겟음
=> [Hotfix] Change to email

src/main/java/com/springboot/intelllij/repository/FreeBoardPreviewRepository.java, src/main/java/com/springboot/intelllij/services/FreeBoardPreviewService.java
이거 다 바꾼줄 알았는데 덜 바뀐놈이 있었음;;
빠르게 머지한다
=> [Hotfix] Change Account to Email

src/main/java/com/springboot/intelllij/controller/UserController.java, src/main/java/com/springboot/intelllij/services/AccountService.java, src/main/java/com/springboot/intelllij/utils/CommentComparator.java
fix https://github.com/wanna-go-home/Issue/issues/60
내가 쓴 댓글이여서, freeboard Controller / reviewboard Controller 어느쪽에도 넣기 애매해서,
일단 account Controller 밑에 두었음. 
좋은 생각은 아닌거 같아서 아래와 같은 리팩토링 방법이 있을것으로 예상됨. 의견부탁
1. article comment / review board comment 나누어서 하기 -> 클라 UX개판될것같음
2. comment controller 로 독립시키기 -> 그러면 기존 article comment / review board comment도 이쪽으로 이사 해야...? 
- path: /api/user/comments/me
- param: 없음
- result 
```json
[
{
"id": 1,
"email": "admin@admin.com",
"postId": 1,
"content": "first comment",
"likeCnt": 0,
"createdAt": "2020-11-01T23:26:06.600Z",
"depth": 0,
"bundleId": 1,
"bundleSize": 0
},
{
"id": 2,
"email": "admin@admin.com",
"postId": 2,
"content": "second comment",
"likeCnt": 0,
"createdAt": "2020-11-01T23:29:55.872Z",
"depth": 0,
"bundleId": 2,
"bundleSize": 0
},
{
"id": …
```
=> [Issue - 60] My comments

src/main/java/com/springboot/intelllij/controller/FreeBoardController.java, src/main/java/com/springboot/intelllij/controller/ReviewBoardController.java, src/main/java/com/springboot/intelllij/controller/UserController.java
fix https://github.com/wanna-go-home/Issue/issues/77
- 기존에 있던 내 잡글 / 내 리뷰 API 경로를 /api/user 밑으로 옮김
=> [Feature] Issue-77 / move APIs

src/main/java/com/springboot/intelllij/controller/UserController.java, src/main/java/com/springboot/intelllij/services/AccountService.java
fix https://github.com/wanna-go-home/Issue/issues/82
- 내정보수정(닉네임 수정) API 만듬
* 닉네임말고 내정보 수정할게 있나?
- 중복되는 부분 Method Extract
=> [Feature] Issue-82 / Modify NickName

src/main/java/com/springboot/intelllij/domain/BoardBaseEntity.java, src/main/java/com/springboot/intelllij/domain/CommentBaseEntity.java, src/main/java/com/springboot/intelllij/services/FreeBoardCommentService.java, src/main/java/com/springboot/intelllij/services/ReviewBoardCommentService.java
fix https://github.com/wanna-go-home/Issue/issues/100
-대댓글 삭제시 bundleSize 감소
=> [Feature] Issue-100 / Decrease bundleSize

src/main/java/com/springboot/intelllij/controller/FreeBoardController.java, src/main/java/com/springboot/intelllij/controller/ReviewBoardController.java, src/main/java/com/springboot/intelllij/services/FreeBoardCommentService.java, src/main/java/com/springboot/intelllij/services/ReviewBoardCommentService.java
fix https://github.com/wanna-go-home/Issue/issues/103
=> [Feature] Issue-103 / Change comment put

src/main/java/com/springboot/intelllij/controller/UserController.java, src/main/java/com/springboot/intelllij/services/AccountService.java
=> [Feature] All comments

src/main/java/com/springboot/intelllij/constant/LikeableTables.java, src/main/java/com/springboot/intelllij/constant/RESTPath.java, src/main/java/com/springboot/intelllij/controller/FreeBoardController.java, src/main/java/com/springboot/intelllij/controller/LensInfoController.java, src/main/java/com/springboot/intelllij/controller/LikePostCommentController.java, src/main/java/com/springboot/intelllij/controller/ReviewBoardController.java, src/main/java/com/springboot/intelllij/controller/UserController.java, src/main/java/com/springboot/intelllij/domain/AccountEntity.java, src/main/java/com/springboot/intelllij/domain/CommentBaseEntity.java, src/main/java/com/springboot/intelllij/domain/FreeBoardCommentEntity.java, src/main/java/com/springboot/intelllij/domain/FreeBoardEntity.java, src/main/java/com/springboot/intelllij/domain/LikedHistoryEntity.java, src/main/java/com/springboot/intelllij/domain/ReviewBoardEntity.java, src/main/java/com/springboot/intelllij/repository/FreeBoardCommentRepository.java, src/main/java/com/springboot/intelllij/repository/FreeBoardRepository.java, src/main/java/com/springboot/intelllij/repository/LikeHistoryRepository.java, src/main/java/com/springboot/intelllij/repository/ReviewBoardCommentRepository.java, src/main/java/com/springboot/intelllij/repository/ReviewBoardRepository.java, src/main/java/com/springboot/intelllij/services/LikePostCommentService.java
FreeBoard, FreeBoardComment, ReviewBoard, ReviewBoardComment
총 4개의 table에 POST like, DELETE like API 2개씩 해서 총 8개의 API를 추가하는 PR
already_liked flag는 주어지지 않지만 동일 user에 대한 중복 like는 동작하지 않고 그냥 200 Response가 넘어감
=> Like post and comment

src/main/java/com/springboot/intelllij/controller/UserController.java, src/main/java/com/springboot/intelllij/services/ReviewBoardPreviewService.java
- 이슈 만들기 전에 바로 추가 해버렸삼
- 내가 쓴 리뷰에 렌즈 정보 추가함
- Result
```json
[
{
"id": 1,
"accountId": 1,
"title": "review_board ahha",
"content": "slom",
"viewCnt": 0,
"likeCnt": 0,
"replyCnt": 0,
"createdAt": "2021-01-02T05:05:54.418Z",
"nickname": "SuperSuperUser",
"lensId": 27,
"lensEntity": {
"lensId": 27,
"name": "바슈롬 레이셀 (크리스탈 브라운)",
"price": 27750,
"graphicDia": 12.9,
"productImage": [
"https://d3w2op3lb880hy.cloudfront.net/wp-content/uploads/2018/09/359_shop1_557873.jpg"
],
"perPackage": 30,
"reviewCnt": 1220,
"bc": 8.6,
"dia": 14.2,
"url": "https://www.lensgogo.com/shop/%eb%b0%94%ec%8a%88%eb%a1%ac-%eb%a0%88%ec%9d%b4%ec%85%80-%ed%81%ac%eb%a6%ac%ec%8a%a4%ed%83%88-%eb%b8%8c%eb%9d%bc%ec%9a%b4/",
"demonstrationImage": [
"https://i1319.photobucket.com/albums/t667/biancazen2/2017%2010/Key%20Visual%20fo …
```
=> [Feature] Add LensInfo in review/me

src/main/java/com/springboot/intelllij/domain/BaseEntity.java, src/main/java/com/springboot/intelllij/domain/BoardBaseEntity.java, src/main/java/com/springboot/intelllij/domain/CommentBaseEntity.java, src/main/java/com/springboot/intelllij/services/FreeBoardCommentService.java, src/main/java/com/springboot/intelllij/services/FreeBoardPreviewService.java, src/main/java/com/springboot/intelllij/services/FreeBoardService.java, src/main/java/com/springboot/intelllij/services/ReviewBoardCommentService.java, src/main/java/com/springboot/intelllij/services/ReviewBoardPreviewService.java, src/main/java/com/springboot/intelllij/utils/EntityUtils.java
- entity refactoring을 하여 공통 attribute를 한데 모았습니다.
- comment, post 모두 적용했습니다.
=> Fix wanna-go-home/issue#75 : add isAuthor flag

src/main/java/com/springboot/intelllij/controller/ReviewBoardController.java, src/main/java/com/springboot/intelllij/domain/ReviewBoardViewWithLensInfoEntity.java, src/main/java/com/springboot/intelllij/services/ReviewBoardPreviewService.java, src/main/java/com/springboot/intelllij/services/ReviewBoardService.java
1. 리뷰 전체 가져오기
2. 리뷰 하나 가져오기
3. 내가 쓴 리뷰 가져오기
다했나? 해치웠나?
=> [Hotfix] Change to LensPreview in Review

src/main/java/com/springboot/intelllij/controller/UserController.java, src/main/java/com/springboot/intelllij/domain/UserModifyDTO.java, src/main/java/com/springboot/intelllij/services/AccountService.java
- 유저 닉네임 수정정보를 Body로 받도록 수정
- Body로 바꾸는김에 수정되는 정보 처리할 DTO 만듬
- 나중에 바꿀 정보 추가되면 저기에 추가해서 하면 될듯
=> [Hotfix] Modify Nickname

src/main/java/com/springboot/intelllij/domain/BaseEntity.java, src/main/java/com/springboot/intelllij/domain/BoardBaseEntity.java
=> [Hotfix] Free board Comment / Article

src/main/java/com/springboot/intelllij/domain/CommentBaseEntity.java
=> [Hotfix] Comment post default value

src/main/java/com/springboot/intelllij/repository/FreeBoardCommentRepository.java, src/main/java/com/springboot/intelllij/repository/ReviewBoardCommentRepository.java, src/main/java/com/springboot/intelllij/services/FreeBoardCommentService.java, src/main/java/com/springboot/intelllij/services/ReviewBoardCommentService.java
- 대댓글을 가져올때 아예 시간순으로 가져오도록 수정함
=> [Hotfix] Fix bundle sort

src/main/java/com/springboot/intelllij/repository/FreeBoardCommentRepository.java, src/main/java/com/springboot/intelllij/repository/FreeBoardRepository.java, src/main/java/com/springboot/intelllij/repository/ReviewBoardCommentRepository.java, src/main/java/com/springboot/intelllij/repository/ReviewBoardRepository.java, src/main/java/com/springboot/intelllij/services/LikePostCommentService.java
Close wanna-go-home/issue#158
- increaseLikeCnt, decreaseLikeCnt를 제거함
- Response에 Entity정보를 담아주기 위해 repository.save method를 사용하도록 변경
- EntityUtils을 사용해서 isLiked, isAuthor flag 넣어주는건 어노테이션으로 빼던가 해야지 칵
=> Send back whole entity after like/dislike API called

src/main/java/com/springboot/intelllij/controller/LikePostCommentController.java, src/main/java/com/springboot/intelllij/domain/FreeBoardViewEntity.java, src/main/java/com/springboot/intelllij/domain/ReviewBoardViewEntity.java, src/main/java/com/springboot/intelllij/services/LikePostCommentService.java
- nickname 붙임
- like / dislike 쪽 API에 ResponseEntity 사용하지 않고 POJO return + @ResponseStatus 사용
=> Send back 'nickname' attribute also

src/main/java/com/springboot/intelllij/constant/CheckUserInfoEnum.java, src/main/java/com/springboot/intelllij/controller/UserController.java, src/main/java/com/springboot/intelllij/domain/CheckAvailableDTO.java, src/main/java/com/springboot/intelllij/services/AccountService.java, src/main/java/com/springboot/intelllij/utils/StringValidationUtils.java
fix wanna-go-home/issue#176
ex)
```json
{
"check_code": 2,
"available": false
}
```
의 형식으로 보내줌.
=> Return availability of user info as a json.

src/main/java/com/springboot/intelllij/controller/ErrorController.java, src/main/java/com/springboot/intelllij/controller/FreeBoardController.java, src/main/java/com/springboot/intelllij/controller/LensInfoController.java, src/main/java/com/springboot/intelllij/controller/LikePostCommentController.java, src/main/java/com/springboot/intelllij/controller/ReviewBoardController.java, src/main/java/com/springboot/intelllij/controller/UserController.java, src/main/java/com/springboot/intelllij/services/AccountService.java, src/main/java/com/springboot/intelllij/services/FreeBoardCommentService.java, src/main/java/com/springboot/intelllij/services/FreeBoardService.java, src/main/java/com/springboot/intelllij/services/ReviewBoardCommentService.java, src/main/java/com/springboot/intelllij/services/ReviewBoardService.java
- @ResponseStatus 어노테이션을 사용함. 비즈니스 로직을 더 가볍게 관리할 수 있어 보였기 때문.
- check nickname과 같은 녀석들은 아직 적용하지 않음. error handler도 만들어 주어야 하기 때문.
=> Refactoring - Use @ResponseStatus annotation

src/main/java/com/springboot/intelllij/domain/AccountBEntity.java, src/main/java/com/springboot/intelllij/domain/UserAuthEntity.java, src/main/java/com/springboot/intelllij/repository/AccountBRepository.java, src/main/java/com/springboot/intelllij/repository/UserAuthRepository.java
새 table 디비에 밀어넣고 entity, repository 만듦.
account는 일단 냅두고
account_b라는 이름으로 만들었는데
구현좀 되면 account 날리고 db 이름만 바꾸면 될듯
=> Add entities and repositories for user auth process
